// Copyright IBM Corp. 2025
// SPDX-License-Identifier: MPL-2.0

syntax = "proto3";
package envelope;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/hashicorp/vault-envelope-encryption-sdk;envelope";

message Header {
  uint32 version = 1;
  oneof data {
    HeaderV1 v1 = 2;
  }
}

message KeyData {
  optional string namespace = 1;
  optional string mount_path = 2;
  optional string key_name = 3;
  uint32 key_version = 4;
  bytes edk = 5;
}

message AlgorithmParameters {
  string hkdfAlgo = 1;
  uint32 ciphertextSegmentSize = 2;
}

message HeaderV1 {
  string algorithm = 1;
  optional AlgorithmParameters algo_params = 2;
  string mime_type = 3;
  string encoding = 4;
  google.protobuf.Timestamp created = 5;
  KeyData key_data = 6;
  bytes salt = 7;
  bytes nonce_prefix = 8;
  optional google.protobuf.Struct metadata = 9;
  optional uint64 length = 10;
}
