name: build

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release/**'

permissions:
  contents: read

env:
  GOPRIVATE: github.com/hashicorp/*

jobs:
  build:
    runs-on: [ 'self-hosted', 'small', 'linux' ]
    env:
      TEST_RESULTS: "/tmp/test-results/gotestsum-report.xml"
    permissions:
      id-token: write # Note: this permission is explicitly required for Vault auth
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: ".go-version"
          cache: true
      - run: go version

      - name: Install CI Tools
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: make bootstrap

      - name: Build & test
        env:
          GOPRIVATE: github.com/hashicorp/*
        run: |
          set -eux -o pipefail

          go build ./...

          go install gotest.tools/gotestsum@v1.9.0
          CGO_ENABLED=1 \
            gotestsum --format=short-verbose --junitfile "${TEST_RESULTS}" -- \
              -timeout=10m \
              -parallel=20 \
              ./...

      - name: Race test
        run: |
          make test-race

      - name: Run code coverage
        run: make cover

      - name: Archive code coverage results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: code-coverage
          path: coverage.txt

  publish_code_coverage:
    name: "Publish code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents:      read
      actions:       read
      pull-requests: write
    steps:
      - name: Publish code coverage report to PR
        continue-on-error: true
        uses: fgrosse/go-coverage-report@8c1d1a09864211d258937b1b1a5b849f7e4f2682 # v1.2.0