name: Linting workflows

on:
  push:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ['self-hosted', 'small', 'linux']
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: "Check GitHub workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint@sha256:3f24bf9d72ca67af6f9f8f3cc63b0e24621b57bf421cecfc452c3312e32b68cc # 1.6.24
        with:
          args: -color